// Generated by nuxt-seo-utils

declare module 'nitropack' {
  interface NitroRouteRules {
     seoMeta?: import('../../node_modules/@unhead/schema/dist/index.mjs').UseSeoMetaInput
     head?: import('../../node_modules/@unhead/schema/dist/index.mjs').Head
  }
  interface NitroRouteConfig {
    seoMeta?: import('../../node_modules/@unhead/schema/dist/index.mjs').UseSeoMetaInput
    head?: import('../../node_modules/@unhead/schema/dist/index.mjs').Head
  }
}

declare module '@nuxt/schema' {
  interface AppHeadMetaObject { seoMeta?: import('../../node_modules/@unhead/schema/dist/index.mjs').UseSeoMetaInput }
}

declare module 'nuxt/schema' {
  interface AppHeadMetaObject { seoMeta?: import('../../node_modules/@unhead/schema/dist/index.mjs').UseSeoMetaInput }
}

export {}
