// Generated by nuxt-seo-utils.assets

declare module '#app' {
  import { HeadEntry, HeadTag } from '@unhead/schema'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}
declare module '@unhead/schema' {

  type PublicFiles = '/_robots.txt' | '/favicon.ico' | '/og-img.jpg' | '/fonts/Infra-Bold.woff' | '/fonts/Infra-ExtraBold.woff' | '/fonts/Infra-Medium.woff' | '/fonts/Infra-Regular.woff' | '/fonts/Infra-SemiBold.woff' | '/svg/arrow-right-tan.svg' | '/svg/fork-knife.svg' | '/svg/logo-icon-green-dark.svg' | '/svg/money.svg' | '/svg/smile.svg' | '/svg/stars.svg' | '/svg/time.svg' | '/svg/x-tan.svg' | (string & Record<never, never>)
  type JsFiles = (string & Record<never, never>)

  interface SchemaAugmentations {
    link: import('@unhead/schema').UserTagConfigWithoutInnerContent & {
      href: PublicFiles
    }
    script: import('@unhead/schema').TagUserProperties & {
      src: JsFiles
    }
  }
}
export {}
